;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-backward-char
        evil-backward-word-begin
        evil-change
        evil-delete
        evil-delete-char
        evil-forward-char
        evil-insert
        evil-next-line
        evil-normal-state
        evil-paste-after
        evil-previous-line
        evil-previous-visual-line
        evil-substitute
        helm-M-x
        helm-confirm-and-exit-minibuffer
        tern-ac-dot-complete
        ))

(setq mc/cmds-to-run-once
      '(
        evil-force-normal-state
        evil-insert-line
        evil-next-visual-line
        iedit-switch-to-mc-mode
        sp-backward-delete-char
        undo-fu-only-undo
        ))
